const locals = {
  Hospital: "Hospital",
  Escola: "Escola",
  Universidade: "Universidade",
  Tribunal: "Tribunal",
  Estacao_de_Metro: "Estação de Metrô",
  Museu: "Museu",
  Biblioteca: "Biblioteca",
  Escola_Municipal: "Escola Municipal",
  Delegacia_de_Policia: "Delegacia de Polícia",
  Agencia_dos_Correios: "Agência dos Correios",
  Banco: "Banco",
  Santuario: "Santuário",
  Parque: "Parque",
  Aeroporto: "Aeroporto",
  Rodoviaria: "Rodoviária",
  Shopping_Center: "Shopping Center",
  Clinica: "Clínica",
  Embaixada: "Embaixada",
  Camara_Municipal: "Câmara Municipal",
  Prefeitura: "Prefeitura",
  Tribunal_Eleitoral: "Tribunal Eleitoral",
  Teatro: "Teatro",
  Fundacao: "Fundação",
  Centro_Cultural: "Centro Cultural",
  Supermercado: "Supermercado",
  Estadio: "Estádio",
  Praca: "Praça",
  Instituto: "Instituto",
  Ministerio: "Ministério",
  Forum: "Fórum",
  Receita_Federal: "Receita Federal",
  Faculdade: "Faculdade",
  Jardim_Botanico: "Jardim Botânico",
  Zoologico: "Zoológico",
  Escola_Tecnica: "Escola Técnica",
  Senado: "Senado",
  Comunidade: "Comunidade",
  INSS: "INSS",
  Centro_Comercial: "Centro Comercial",
  Centro_de_Convencoes: "Centro de Convenções",
  Subprefeitura: "Subprefeitura",
  Associacao: "Associação",
  Academia_de_Ginastica: "Academia de Ginástica",
  Agencia_de_Turismo: "Agência de Turismo",
  Auditorio: "Auditório",
  Hospital_Psiquiatrico: "Hospital Psiquiátrico",
  Centro_Esportivo: "Centro Esportivo",
  Cineclube: "Cineclube",
  Conservatorio_de_Musica: "Conservatório de Música",
  Cooperativa: "Cooperativa",
};

export { locals };
